[package]
name = "muon"
version = "0.0.1"
license = "MIT OR Apache-2.0"
keywords = ["serde"]
categories = ["encoding"]
edition = "2018"
publish = false

[dependencies]
num-traits = "0.2"
serde = "1.0"

[dev-dependencies]
serde_derive = "1.0"
